config/routes.rb
Rails.application.routes.draw do
  
  resources :images
  
  root "images#index"

end

app/models/image.rb
class Image < ActiveRecord::Base

  mount_uploader :source, PicturesUploader
  
  validates :name, presence: true, length: { minimum: 5 }
  
  validates :source, presence: true
  validates_processing_of :source
  validate :source_size_validation
  
private

  def source_size_validation
    errors[:source] << "should be less than 50KB" if source.size > 0.048828125.megabytes
  end  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    
    if @image.save
      redirect_to images_path
    else
      render "new"
    end    
  end
  
private

  def image_params
    params.require(:image).permit(:name, :source)
  end
      
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/index.html.erb
<h1>Images</h1>

<%= link_to "Add Image", new_image_path %>

<br/>
<br/>

<% @images.each do |image| %>
  
  <p>
  	<%= image.name %>:
  </p>
  
  <p>	
    <%= image_tag image.source.url %>
  </p>
  
<% end %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= form_for :image, url: images_path do |f| %>

  <% if @image.errors.any? %>
    
      <h2>
        <%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:
      </h2>
      <ul>
        <% @image.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    
  <% end %>
  
  <p>
    <%= f.label :name %>
  </p>
  
  <p>
    <%= f.text_field :name %>
  </p>
  
  <p>  
    <%= f.label :source %>
  </p>
  
  <p>  
    <%= f.file_field :source %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
    
<% end %>

<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Images</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%# Commenting this line due to some Windows bug %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
  
</head>
<body>

<%= yield %>

</body>
</html>